import { ApiError } from "@/lib/api";

const MESSAGES: Record<string, string> = {
  INVALID_CREDENTIALS: "Email hoặc mật khẩu không đúng.",
  ACCOUNT_INACTIVE: "Tài khoản đã bị khoá. Vui lòng liên hệ quản trị viên.",
  UNAUTHORIZED: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  CSRF_INVALID: "Phiên làm việc đã hết hạn. Vui lòng tải lại trang và thử lại.",
  RATE_LIMIT_EXCEEDED: "Bạn thao tác quá nhanh. Vui lòng đợi một phút rồi thử lại.",
  PERMISSION_DENIED: "Bạn không có quyền thực hiện thao tác này.",
  CURRENT_PASSWORD_INVALID: "Mật khẩu hiện tại không đúng.",
  VALIDATION_ERROR: "Thông tin nhập chưa hợp lệ. Vui lòng kiểm tra lại.",
  INVALID_FULL_NAME: "Họ và tên không hợp lệ.",
  EMAIL_ALREADY_EXISTS: "Email này đã có tài khoản.",
  STUDENT_CODE_ALREADY_EXISTS: "Mã sinh viên này đã được dùng cho tài khoản khác.",
  USER_NOT_FOUND: "Không tìm thấy tài khoản.",
  USER_INACTIVE: "Tài khoản này đang bị khoá.",
  INVALID_SORT: "Kiểu sắp xếp không hợp lệ.",
  CLUB_NOT_FOUND: "Không tìm thấy câu lạc bộ.",
  CLUB_INACTIVE: "Câu lạc bộ đang tạm ngừng hoạt động.",
  CLUB_CODE_ALREADY_EXISTS: "Mã câu lạc bộ đã tồn tại.",
  INVALID_CLUB_CODE: "Mã câu lạc bộ không hợp lệ.",
  INVALID_CLUB_NAME: "Tên câu lạc bộ không hợp lệ.",
  APPLICATION_ALREADY_PENDING: "Bạn đã có đơn đang chờ duyệt ở câu lạc bộ này.",
  APPLICATION_ALREADY_REVIEWED: "Đơn này đã được xét duyệt.",
  APPLICATION_CANNOT_BE_CANCELLED: "Đơn này không thể huỷ nữa.",
  CLUB_APPLICATION_NOT_FOUND: "Không tìm thấy đơn đăng ký.",
  ALREADY_CLUB_MEMBER: "Bạn đã là thành viên của câu lạc bộ này.",
  MEMBERSHIP_ALREADY_EXISTS: "Người này đã là thành viên của câu lạc bộ.",
  DUPLICATE_MEMBERSHIP: "Người này đã là thành viên của câu lạc bộ.",
  MEMBERSHIP_NOT_FOUND: "Không tìm thấy thành viên.",
  MEMBERSHIP_NOT_ACTIVE: "Thành viên không còn hoạt động.",
  MEMBERSHIP_ALREADY_LEFT: "Thành viên đã rời câu lạc bộ.",
  DEPARTMENT_NOT_FOUND: "Không tìm thấy ban.",
  DEPARTMENT_INACTIVE: "Ban đang tạm ngừng hoạt động.",
  DEPARTMENT_NAME_ALREADY_EXISTS: "Tên ban đã tồn tại trong câu lạc bộ.",
  INVALID_DEPARTMENT_NAME: "Tên ban không hợp lệ.",
  DEPARTMENT_MEMBER_ALREADY_EXISTS: "Thành viên đã ở trong ban này.",
  DEPARTMENT_MEMBER_NOT_FOUND: "Thành viên không thuộc ban này.",
  CROSS_CLUB_ASSIGNMENT: "Không thể xếp thành viên vào ban của câu lạc bộ khác.",
  CROSS_CLUB_MOVE: "Không thể chuyển thành viên sang ban của câu lạc bộ khác.",
  SAME_DEPARTMENT: "Thành viên đã ở ban này.",
  PERMISSION_ALREADY_GRANTED: "Quyền này đã được cấp.",
  PERMISSION_NOT_FOUND: "Không tìm thấy quyền.",
  PERMISSION_GRANT_NOT_FOUND: "Không tìm thấy quyền đã cấp.",
  PERMISSION_INACTIVE: "Quyền này đang bị tắt.",
  PERMISSION_SCOPE_MISMATCH: "Phạm vi quyền không phù hợp.",
  INVALID_PERMISSION_SCOPE: "Phạm vi quyền không hợp lệ.",
  INVALID_SCOPE_TARGET: "Đối tượng áp dụng quyền không hợp lệ.",
  AMBIGUOUS_PERMISSION_GRANT: "Có nhiều quyền trùng nhau, vui lòng chọn cụ thể.",
  ROLE_NOT_FOUND: "Không tìm thấy vai trò.",
  ROLE_INACTIVE: "Vai trò đang bị tắt.",
  ROLE_ALREADY_ASSIGNED: "Vai trò này đã được gán.",
  ROLE_ASSIGNMENT_NOT_FOUND: "Không tìm thấy vai trò đã gán.",
  ROLE_CODE_ALREADY_EXISTS: "Mã vai trò đã tồn tại.",
  INVALID_ROLE_NAME: "Tên vai trò không hợp lệ.",
  ROLE_SCOPE_MISMATCH: "Phạm vi vai trò không phù hợp.",
  ROLE_PERMISSION_SCOPE_MISMATCH: "Vai trò chứa quyền vượt phạm vi cho phép.",
  SYSTEM_ROLE_IMMUTABLE: "Không thể sửa vai trò hệ thống.",
  DOCUMENT_NOT_FOUND: "Không tìm thấy tài liệu.",
  DOCUMENT_DELETED: "Tài liệu đã bị xoá. Khôi phục trước khi thao tác.",
  DOCUMENT_NOT_DELETED: "Tài liệu này chưa bị xoá.",
  DOCUMENT_NAME_ALREADY_EXISTS: "Đã có tài liệu cùng tên trong câu lạc bộ. Hãy đổi tên hoặc tải lên phiên bản mới.",
  INVALID_DOCUMENT_NAME: "Tên file không hợp lệ (không chứa đường dẫn, ký tự đặc biệt và phải có đuôi file).",
  SUSPICIOUS_DOCUMENT_NAME: "Tên file có dấu hiệu giả mạo loại file nên bị từ chối.",
  UNSUPPORTED_DOCUMENT_TYPE: "Loại file này không được phép tải lên.",
  DOCUMENT_CONTENT_MISMATCH: "Nội dung file không khớp với đuôi file.",
  EMPTY_DOCUMENT: "File rỗng.",
  DOCUMENT_TOO_LARGE: "File vượt quá dung lượng cho phép (20 MB).",
  DOCUMENT_TYPE_CHANGED: "Phiên bản mới phải cùng loại file với tài liệu.",
  DOCUMENT_VERSION_CONFLICT: "Tài liệu vừa được người khác cập nhật. Vui lòng tải lại và thử lại.",
  DOCUMENT_VERSION_UNCHANGED: "File giống hệt phiên bản hiện tại.",
  DOCUMENT_VERSION_NOT_FOUND: "Không tìm thấy phiên bản này.",
  INVALID_DOCUMENT_VERSION: "Số phiên bản không hợp lệ.",
  INVALID_APP_DETAIL_KEY: "appDetailKey chỉ gồm chữ thường, số, dấu gạch dưới và dấu chấm (ví dụ club.rules).",
  DOCUMENT_STORAGE_ERROR: "Kho lưu trữ đang gặp sự cố. Vui lòng thử lại sau.",
  DATA_CONFLICT: "Dữ liệu bị trùng hoặc vừa thay đổi. Vui lòng tải lại.",
  INTERNAL_ERROR: "Hệ thống đang gặp sự cố. Vui lòng thử lại sau.",
};

const BY_STATUS: Record<number, string> = {
  400: "Yêu cầu không hợp lệ. Vui lòng kiểm tra lại thông tin.",
  401: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  403: "Bạn không có quyền thực hiện thao tác này.",
  404: "Không tìm thấy dữ liệu.",
  409: "Dữ liệu bị trùng hoặc vừa thay đổi. Vui lòng tải lại.",
  413: "File quá lớn.",
  429: "Bạn thao tác quá nhanh. Vui lòng đợi một chút.",
};

export function errorMessage(error: unknown): string {
  if (error instanceof ApiError) {
    if (error.code && MESSAGES[error.code]) return MESSAGES[error.code];
    if (BY_STATUS[error.status]) return BY_STATUS[error.status];
    return error.status >= 500 ? MESSAGES.INTERNAL_ERROR : "Đã có lỗi xảy ra. Vui lòng thử lại.";
  }
  if (error instanceof TypeError) return "Không kết nối được máy chủ. Vui lòng kiểm tra mạng và thử lại.";
  return "Đã có lỗi xảy ra. Vui lòng thử lại.";
}
