package com.vju.club.modules.user.mapper;

import com.vju.club.modules.user.dto.response.UserResponse;
import com.vju.club.modules.user.entity.User;
import org.mapstruct.Mapper;

/** Entity → DTO mapping for users; the implementation is generated by MapStruct at compile time. */
@Mapper
public interface UserMapper {
    UserResponse toResponse(User user);
}
