spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/club}
    username: ${DB_USERNAME:club}
    password: ${DB_PASSWORD:club_local}
